### ISSUE TITLE
allow requiring one property if another property is set

### ISSUE THREAD

**Issue by gdruck** [yummly/validaze#8]
i.e. `{:required? [:when "content_id" some?]}`

**Comment by johanatan** [comment]
@gdruck  this one was finished a while back yes? is there anything more to be done for it?

**Comment by gdruck** [comment]
the syntax suggested above doesn't work, but I don't remember if we decided to do it another way ...

**Comment by johanatan** [comment]
@gdruck you'll need to update to 1.3.1 when you want to use this feature.
